version: '3.8'
services:
  mysql:
    image: mysql:5.7 # You can use any desired MySQL version
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
      MYSQL_DATABASE: test_database
    ports:
      - "3306:3306" # Map the host machine's port to the MySQL container's port
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge


volumes:
  mysql-data: