version: '3.8'
services:
  node-app:
    image: akashgond3112/leovegaschallenge:latest
    container_name: node-app-container
    environment:
      - NODE_ENV=production
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - prisma-migrate
    command: ["dockerize", "-wait", "tcp://mysql:3306", "-timeout", "60s", "npm", "start"]
    networks:
      - mynetwork

  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
      MYSQL_DATABASE: test_database
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  prisma-migrate:
    image: akashgond3112/leovegaschallenge:latest
    depends_on:
      - mysql
    command: ["dockerize", "-wait", "tcp://mysql:3306", "-timeout", "60s", "npx", "prisma", "migrate", "dev", "--name", "init"]
    environment:
      - NODE_ENV=production
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
