apiVersion: apps/v1
kind: Deployment
metadata:
  name: prisma-migrate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prisma-migrate
  template:
    metadata:
      labels:
        app: prisma-migrate
    spec:
      containers:
        - name: prisma-migrate
          image: akashgond3112/leovegaschallenge:latest
          env:
            - name: NODE_ENV
              value: production
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: host
            - name: DB_PORT
              value: "3306"  # Assuming a default MySQL port
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: password
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: dbName
          resources:
            limits:
              cpu: "500m"  # 0.5 CPU cores
              memory: "512Mi"  # 512 Megabytes
            requests:
              cpu: "250m"  # 0.25 CPU cores
              memory: "256Mi"  # 256 Megabytes
          command: ["npx", "prisma", "migrate", "dev", "--name", "init"]
---
apiVersion: v1
kind: Service
metadata:
  name: prisma-migrate-service
spec:
  selector:
    app: prisma-migrate
  ports:
    - port: 80  # You may need to adjust this port based on your application configuration
      targetPort: 80
